language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  local_dir: build
  keep_history: false
  edge: true #opt in dpl v2
  on:
    branch: master
notifications:
  webhooks: https://www.travisbuddy.com/
